// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: pb/mailbaby.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_mailbaby_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_pb_mailbaby_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_mailbaby_proto_rawDescGZIP(), []int{8, 0}
}

// Attachment represents a file attached to an email.
type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Inline        bool                   `protobuf:"varint,4,opt,name=inline,proto3" json:"inline,omitempty"`
	ContentId     string                 `protobuf:"bytes,5,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_pb_mailbaby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mailbaby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_pb_mailbaby_proto_rawDescGZIP(), []int{0}
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Attachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Attachment) GetInline() bool {
	if x != nil {
		return x.Inline
	}
	return false
}

func (x *Attachment) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

// SendMailRequest represents a single email delivery request.
type SendMailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	FromName      string                 `protobuf:"bytes,4,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	ReplyTo       string                 `protobuf:"bytes,5,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	To            []string               `protobuf:"bytes,6,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []string               `protobuf:"bytes,7,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc           []string               `protobuf:"bytes,8,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject       string                 `protobuf:"bytes,9,opt,name=subject,proto3" json:"subject,omitempty"`
	TextBody      string                 `protobuf:"bytes,10,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	HtmlBody      string                 `protobuf:"bytes,11,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,12,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Attachments   []*Attachment          `protobuf:"bytes,13,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Tags          []string               `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,15,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Async         bool                   `protobuf:"varint,16,opt,name=async,proto3" json:"async,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailRequest) Reset() {
	*x = SendMailRequest{}
	mi := &file_pb_mailbaby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailRequest) ProtoMessage() {}

func (x *SendMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mailbaby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailRequest.ProtoReflect.Descriptor instead.
func (*SendMailRequest) Descriptor() ([]byte, []int) {
	return file_pb_mailbaby_proto_rawDescGZIP(), []int{1}
}

func (x *SendMailRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendMailRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SendMailRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendMailRequest) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *SendMailRequest) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *SendMailRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendMailRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendMailRequest) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *SendMailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendMailRequest) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *SendMailRequest) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *SendMailRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *SendMailRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendMailRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SendMailRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SendMailRequest) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

// SendMailResponse represents the result of an email delivery request.
type SendMailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "sent" or "queued"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	SentAt        int64                  `protobuf:"varint,4,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"` // Unix timestamp in seconds or nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailResponse) Reset() {
	*x = SendMailResponse{}
	mi := &file_pb_mailbaby_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailResponse) ProtoMessage() {}

func (x *SendMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mailbaby_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailResponse.ProtoReflect.Descriptor instead.
func (*SendMailResponse) Descriptor() ([]byte, []int) {
	return file_pb_mailbaby_proto_rawDescGZIP(), []int{2}
}

func (x *SendMailResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendMailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendMailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMailResponse) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

// BatchSendMailRequest represents a batch of email delivery requests.
type BatchSendMailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []*SendMailRequest     `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	Async         bool                   `protobuf:"varint,2,opt,name=async,proto3" json:"async,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSendMailRequest) Reset() {
	*x = BatchSendMailRequest{}
	mi := &file_pb_mailbaby_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSendMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSendMailRequest) ProtoMessage() {}

func (x *BatchSendMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mailbaby_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSendMailRequest.ProtoReflect.Descriptor instead.
func (*BatchSendMailRequest) Descriptor() ([]byte, []int) {
	return file_pb_mailbaby_proto_rawDescGZIP(), []int{3}
}

func (x *BatchSendMailRequest) GetEmails() []*SendMailRequest {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *BatchSendMailRequest) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

// BatchSendMailResponse represents the result of a batch email delivery request.
type BatchSendMailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Succeeded     int32                  `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Results       []*SendMailResponse    `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSendMailResponse) Reset() {
	*x = BatchSendMailResponse{}
	mi := &file_pb_mailbaby_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSendMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSendMailResponse) ProtoMessage() {}

func (x *BatchSendMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mailbaby_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSendMailResponse.ProtoReflect.Descriptor instead.
func (*BatchSendMailResponse) Descriptor() ([]byte, []int) {
	return file_pb_mailbaby_proto_rawDescGZIP(), []int{4}
}

func (x *BatchSendMailResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BatchSendMailResponse) GetSucceeded() int32 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

func (x *BatchSendMailResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BatchSendMailResponse) GetResults() []*SendMailResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

// PingRequest represents a ping/liveness probe.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_pb_mailbaby_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mailbaby_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_pb_mailbaby_proto_rawDescGZIP(), []int{5}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PingResponse represents the ping response.
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_pb_mailbaby_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mailbaby_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_pb_mailbaby_proto_rawDescGZIP(), []int{6}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HealthCheckRequest for service health check.
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pb_mailbaby_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mailbaby_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pb_mailbaby_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// HealthCheckResponse for service health check.
type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=mailbaby.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Details       map[string]string                 `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pb_mailbaby_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mailbaby_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pb_mailbaby_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_pb_mailbaby_proto protoreflect.FileDescriptor

const file_pb_mailbaby_proto_rawDesc = "" +
	"\n" +
	"\x11pb/mailbaby.proto\x12\vmailbaby.v1\"\x96\x01\n" +
	"\n" +
	"Attachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x16\n" +
	"\x06inline\x18\x04 \x01(\bR\x06inline\x12\x1d\n" +
	"\n" +
	"content_id\x18\x05 \x01(\tR\tcontentId\"\xf8\x04\n" +
	"\x0fSendMailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x1b\n" +
	"\tfrom_name\x18\x04 \x01(\tR\bfromName\x12\x19\n" +
	"\breply_to\x18\x05 \x01(\tR\areplyTo\x12\x0e\n" +
	"\x02to\x18\x06 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\a \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\b \x03(\tR\x03bcc\x12\x18\n" +
	"\asubject\x18\t \x01(\tR\asubject\x12\x1b\n" +
	"\ttext_body\x18\n" +
	" \x01(\tR\btextBody\x12\x1b\n" +
	"\thtml_body\x18\v \x01(\tR\bhtmlBody\x12C\n" +
	"\aheaders\x18\f \x03(\v2).mailbaby.v1.SendMailRequest.HeadersEntryR\aheaders\x129\n" +
	"\vattachments\x18\r \x03(\v2\x17.mailbaby.v1.AttachmentR\vattachments\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12F\n" +
	"\bmetadata\x18\x0f \x03(\v2*.mailbaby.v1.SendMailRequest.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05async\x18\x10 \x01(\bR\x05async\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x10SendMailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x17\n" +
	"\asent_at\x18\x04 \x01(\x03R\x06sentAt\"b\n" +
	"\x14BatchSendMailRequest\x124\n" +
	"\x06emails\x18\x01 \x03(\v2\x1c.mailbaby.v1.SendMailRequestR\x06emails\x12\x14\n" +
	"\x05async\x18\x02 \x01(\bR\x05async\"\x9c\x01\n" +
	"\x15BatchSendMailResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1c\n" +
	"\tsucceeded\x18\x02 \x01(\x05R\tsucceeded\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x127\n" +
	"\aresults\x18\x04 \x03(\v2\x1d.mailbaby.v1.SendMailResponseR\aresults\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"^\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xb3\x02\n" +
	"\x13HealthCheckResponse\x12F\n" +
	"\x06status\x18\x01 \x01(\x0e2..mailbaby.v1.HealthCheckResponse.ServingStatusR\x06status\x12G\n" +
	"\adetails\x18\x02 \x03(\v2-.mailbaby.v1.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x032\xb5\x02\n" +
	"\vMailService\x12C\n" +
	"\x04Send\x12\x1c.mailbaby.v1.SendMailRequest\x1a\x1d.mailbaby.v1.SendMailResponse\x12R\n" +
	"\tSendBatch\x12!.mailbaby.v1.BatchSendMailRequest\x1a\".mailbaby.v1.BatchSendMailResponse\x12;\n" +
	"\x04Ping\x12\x18.mailbaby.v1.PingRequest\x1a\x19.mailbaby.v1.PingResponse\x12P\n" +
	"\vHealthCheck\x12\x1f.mailbaby.v1.HealthCheckRequest\x1a .mailbaby.v1.HealthCheckResponseB\x13Z\x11mailbaby/proto;pbb\x06proto3"

var (
	file_pb_mailbaby_proto_rawDescOnce sync.Once
	file_pb_mailbaby_proto_rawDescData []byte
)

func file_pb_mailbaby_proto_rawDescGZIP() []byte {
	file_pb_mailbaby_proto_rawDescOnce.Do(func() {
		file_pb_mailbaby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_mailbaby_proto_rawDesc), len(file_pb_mailbaby_proto_rawDesc)))
	})
	return file_pb_mailbaby_proto_rawDescData
}

var file_pb_mailbaby_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_mailbaby_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pb_mailbaby_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: mailbaby.v1.HealthCheckResponse.ServingStatus
	(*Attachment)(nil),                     // 1: mailbaby.v1.Attachment
	(*SendMailRequest)(nil),                // 2: mailbaby.v1.SendMailRequest
	(*SendMailResponse)(nil),               // 3: mailbaby.v1.SendMailResponse
	(*BatchSendMailRequest)(nil),           // 4: mailbaby.v1.BatchSendMailRequest
	(*BatchSendMailResponse)(nil),          // 5: mailbaby.v1.BatchSendMailResponse
	(*PingRequest)(nil),                    // 6: mailbaby.v1.PingRequest
	(*PingResponse)(nil),                   // 7: mailbaby.v1.PingResponse
	(*HealthCheckRequest)(nil),             // 8: mailbaby.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 9: mailbaby.v1.HealthCheckResponse
	nil,                                    // 10: mailbaby.v1.SendMailRequest.HeadersEntry
	nil,                                    // 11: mailbaby.v1.SendMailRequest.MetadataEntry
	nil,                                    // 12: mailbaby.v1.HealthCheckResponse.DetailsEntry
}
var file_pb_mailbaby_proto_depIdxs = []int32{
	10, // 0: mailbaby.v1.SendMailRequest.headers:type_name -> mailbaby.v1.SendMailRequest.HeadersEntry
	1,  // 1: mailbaby.v1.SendMailRequest.attachments:type_name -> mailbaby.v1.Attachment
	11, // 2: mailbaby.v1.SendMailRequest.metadata:type_name -> mailbaby.v1.SendMailRequest.MetadataEntry
	2,  // 3: mailbaby.v1.BatchSendMailRequest.emails:type_name -> mailbaby.v1.SendMailRequest
	3,  // 4: mailbaby.v1.BatchSendMailResponse.results:type_name -> mailbaby.v1.SendMailResponse
	0,  // 5: mailbaby.v1.HealthCheckResponse.status:type_name -> mailbaby.v1.HealthCheckResponse.ServingStatus
	12, // 6: mailbaby.v1.HealthCheckResponse.details:type_name -> mailbaby.v1.HealthCheckResponse.DetailsEntry
	2,  // 7: mailbaby.v1.MailService.Send:input_type -> mailbaby.v1.SendMailRequest
	4,  // 8: mailbaby.v1.MailService.SendBatch:input_type -> mailbaby.v1.BatchSendMailRequest
	6,  // 9: mailbaby.v1.MailService.Ping:input_type -> mailbaby.v1.PingRequest
	8,  // 10: mailbaby.v1.MailService.HealthCheck:input_type -> mailbaby.v1.HealthCheckRequest
	3,  // 11: mailbaby.v1.MailService.Send:output_type -> mailbaby.v1.SendMailResponse
	5,  // 12: mailbaby.v1.MailService.SendBatch:output_type -> mailbaby.v1.BatchSendMailResponse
	7,  // 13: mailbaby.v1.MailService.Ping:output_type -> mailbaby.v1.PingResponse
	9,  // 14: mailbaby.v1.MailService.HealthCheck:output_type -> mailbaby.v1.HealthCheckResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pb_mailbaby_proto_init() }
func file_pb_mailbaby_proto_init() {
	if File_pb_mailbaby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_mailbaby_proto_rawDesc), len(file_pb_mailbaby_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_mailbaby_proto_goTypes,
		DependencyIndexes: file_pb_mailbaby_proto_depIdxs,
		EnumInfos:         file_pb_mailbaby_proto_enumTypes,
		MessageInfos:      file_pb_mailbaby_proto_msgTypes,
	}.Build()
	File_pb_mailbaby_proto = out.File
	file_pb_mailbaby_proto_goTypes = nil
	file_pb_mailbaby_proto_depIdxs = nil
}
